window.HOLLOWSIDE_SUPABASE_URL = "PASTE_YOUR_SUPABASE_PROJECT_URL_HERE";
window.HOLLOWSIDE_SUPABASE_ANON_KEY = "PASTE_YOUR_SUPABASE_ANON_KEY_HERE";
window.HOLLOWSIDE_SUPABASE_STORAGE_KEY = "hollowside-auth";
